services:
  api:
    build:
      context: ./backend
      dockerfile: Dockerfile.dev
      args:
        UID: "${HOST_UID:-1000}"
        GID: "${HOST_GID:-1000}"
    volumes:
      - ./backend:/rails
      - ./doc:/doc:ro
      - bundle_cache:/usr/local/bundle
    ports:
      - "3000:3000"
    environment:
      RAILS_ENV: development
    stdin_open: true
    tty: true

volumes:
  bundle_cache:
