/**
 * This file was auto-generated by openapi-typescript.
 * Do not make direct changes to the file.
 */

export interface paths {
    "/spots": {
        parameters: {
            query?: never;
            header?: never;
            path?: never;
            cookie?: never;
        };
        /**
         * スポットを検索する
         * @description 条件に合うスポットの一覧を返す（カーソルページネーション）。
         *     doc/api-design.md「設計上の判断 2」の通り、絞り込みには2種類ある。
         *     - 探す軸（area_id・category_id・scene）：クライアントが明示的に送る
         *     - 自分たち軸（stage・budget_range・with_child）：personalize=true を送ると
         *       サーバが会員の情報から補完する。明示パラメータが優先される
         */
        get: operations["listSpots"];
        put?: never;
        post?: never;
        delete?: never;
        options?: never;
        head?: never;
        patch?: never;
        trace?: never;
    };
    "/spots/{id}": {
        parameters: {
            query?: never;
            header?: never;
            path?: never;
            cookie?: never;
        };
        /**
         * スポットの詳細を見る
         * @description スポット1つの詳しい情報を返す。doc/api-design.md「設計上の判断 3」の通り、
         *     「保存済みかどうか」は常に本人の視点のみで判定する
         *     （パートナーがサプライズ保存していてもこのフラグは立たない）。
         */
        get: operations["getSpot"];
        put?: never;
        post?: never;
        delete?: never;
        options?: never;
        head?: never;
        patch?: never;
        trace?: never;
    };
    "/areas": {
        parameters: {
            query?: never;
            header?: never;
            path?: never;
            cookie?: never;
        };
        /**
         * エリア一覧を見る
         * @description 絞り込み（spots.area_id）に使うエリアのマスタを返す。doc/er-and-db-design.md の通り
         *     parent_id による親子構造（例：「渋谷エリア」の子に「代官山」「恵比寿」）を持つが、
         *     レスポンスはフラットな配列で返す。階層はクライアント側が parent_id を辿って組み立てる
         *     （件数が少ないマスタのため、ページングは無い）。
         */
        get: operations["listAreas"];
        put?: never;
        post?: never;
        delete?: never;
        options?: never;
        head?: never;
        patch?: never;
        trace?: never;
    };
    "/categories": {
        parameters: {
            query?: never;
            header?: never;
            path?: never;
            cookie?: never;
        };
        /**
         * カテゴリ一覧を見る
         * @description 絞り込み（spots.category_id）に使うカテゴリのマスタを返す
         *     （件数が少ないマスタのため、ページングは無い）。
         */
        get: operations["listCategories"];
        put?: never;
        post?: never;
        delete?: never;
        options?: never;
        head?: never;
        patch?: never;
        trace?: never;
    };
}
export type webhooks = Record<string, never>;
export interface components {
    schemas: {
        Spot: {
            /** Format: uuid */
            id: string;
            name: string;
            /** Format: uuid */
            area_id: string;
            /** Format: uuid */
            category_id: string;
            /**
             * Format: float
             * @description 「1組のカップル/会員につき、1スポットあたり最新1件」のみを集計した平均
             *     （doc/domain-model.md）。レビューが無ければ null
             */
            average_rating: number | null;
            /** @description 平均評価に数えられているレビューの件数（★の横に添える件数表示に使う） */
            reviews_count: number;
        };
        SpotDetail: components["schemas"]["Spot"] & {
            /**
             * @description 本人が保存済みかどうか（本人視点のみ。パートナーのサプライズは含まない）。
             *     ⚠️未実装：認証導入前は本人を判定できないため、常に false を返す
             *     （認証導入後の別PRで対応する）
             */
            saved: boolean;
        };
        Area: {
            /** Format: uuid */
            id: string;
            name: string;
            /**
             * Format: uuid
             * @description 親エリアのid。最上位エリアは null
             */
            parent_id: string | null;
            /** @description 表示順 */
            position: number;
        };
        AreaList: {
            areas: components["schemas"]["Area"][];
        };
        Category: {
            /** Format: uuid */
            id: string;
            name: string;
            /** @description 表示順 */
            position: number;
        };
        CategoryList: {
            categories: components["schemas"]["Category"][];
        };
        SpotList: {
            spots: components["schemas"]["Spot"][];
            /** @description 次ページが無ければ null */
            next_cursor: string | null;
        };
        /** @description RFC 9457 (Problem Details) 形式。doc/api-design.md「設計上の判断 4」参照 */
        Problem: {
            /** Format: uri */
            type: string;
            title: string;
            status: number;
            request_id?: string;
        };
    };
    responses: {
        /** @description リクエストが不正 */
        BadRequest: {
            headers: {
                [name: string]: unknown;
            };
            content: {
                "application/problem+json": components["schemas"]["Problem"];
            };
        };
        /** @description 対象が存在しない */
        NotFound: {
            headers: {
                [name: string]: unknown;
            };
            content: {
                "application/problem+json": components["schemas"]["Problem"];
            };
        };
    };
    parameters: {
        SpotId: string;
    };
    requestBodies: never;
    headers: never;
    pathItems: never;
}
export type $defs = Record<string, never>;
export interface operations {
    listSpots: {
        parameters: {
            query?: {
                /** @description 探す軸。エリアで絞り込む */
                area_id?: string;
                /** @description 探す軸。カテゴリで絞り込む */
                category_id?: string;
                /**
                 * @description 探す軸。利用シーンで絞り込む。
                 *     ⚠️未実装：sceneはreviewsテーブルの属性でありスポット自体は持たないため、
                 *     reviewsとのjoinが必要。reviews導入後の別PRで対応する（現時点では無視される）
                 */
                scene?: string;
                /**
                 * @description 自分たち軸（ステージ・予算帯・子連れ訪問）をサーバ側で補完するか。
                 *     ⚠️未実装：会員の判定に認証が要るため、認証導入後の別PRで対応する
                 *     （現時点では無視される）
                 */
                personalize?: boolean;
                /** @description 前回のレスポンスの next_cursor */
                cursor?: string;
                limit?: number;
            };
            header?: never;
            path?: never;
            cookie?: never;
        };
        requestBody?: never;
        responses: {
            /** @description スポット一覧 */
            200: {
                headers: {
                    [name: string]: unknown;
                };
                content: {
                    "application/json": components["schemas"]["SpotList"];
                };
            };
            400: components["responses"]["BadRequest"];
        };
    };
    getSpot: {
        parameters: {
            query?: never;
            header?: never;
            path: {
                id: components["parameters"]["SpotId"];
            };
            cookie?: never;
        };
        requestBody?: never;
        responses: {
            /** @description スポット詳細 */
            200: {
                headers: {
                    [name: string]: unknown;
                };
                content: {
                    "application/json": components["schemas"]["SpotDetail"];
                };
            };
            404: components["responses"]["NotFound"];
        };
    };
    listAreas: {
        parameters: {
            query?: never;
            header?: never;
            path?: never;
            cookie?: never;
        };
        requestBody?: never;
        responses: {
            /** @description エリア一覧 */
            200: {
                headers: {
                    [name: string]: unknown;
                };
                content: {
                    "application/json": components["schemas"]["AreaList"];
                };
            };
        };
    };
    listCategories: {
        parameters: {
            query?: never;
            header?: never;
            path?: never;
            cookie?: never;
        };
        requestBody?: never;
        responses: {
            /** @description カテゴリ一覧 */
            200: {
                headers: {
                    [name: string]: unknown;
                };
                content: {
                    "application/json": components["schemas"]["CategoryList"];
                };
            };
        };
    };
}
